#!python -m cmdpy

def ignored_func():
    """this function is ignored by cmdpy because it doesn't start
       with the default command prefix of 'cmd_'
    """


def cmd_echo(args, prefix="Echo: "):
    """echo [args]  - Echo the args you give it
    --prefix=Echo   - set the echo prefix. Default: "Echo: "
    """
    print(prefix + " ".join(args))



